site_name: PureRustRobot Documents

repo_url: https://github.com/PureRustRobot/prr-docs

theme:
  name: material
  palette:
    primary: white
    scheme: slate
  features:
    - navigation.sections
    - navigation.footer
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - tables
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md

  - Node:
    - OverView: Nodes/index.md
    - command controller: Nodes/command_controller.md
    - joy publisher: Nodes/joy_publisher.md
    - keyboard publisher: Nodes/keyboard_publisher.md
    - motor controller: Nodes/motor_controller.md
    - serial transporter: Nodes/serial_transporter.md

  - Libraries:
    - OverView: Libraries/index.md
    - prr msgs: Libraries/prr_msgs.md
    - zenoh manage utils: Libraries/zenoh_manage_utils.md
    - zenoh message generator: Libraries/zenoh_msg_generator.md

  - Contribution:
    - OverView: Contribution/index.md
    - Setup environment: Contribution/DevEnvGuide.md
    - Start Zenoh: Contribution/StartZenoh.md
  - Architecture: Architecture/index.md